application: web592group27
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.(js|css|html|gif|png|jpg|wav|mp3|json))$
  static_files: \1
  upload: .*\.(js|css|html|gif|png|jpg|wav|mp3|json)$
  
- url: /res
  static_dir: res 

- url: .*
  script: main.php
